name: diagram_flow_ai
description: "A multi-platform desktop application for DiagramFlowAI."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/aws_assets_list.txt
    - assets/aws_icons/Res_IoT/
    - assets/aws_icons/Res_Quantum-Technologies/
    - assets/aws_icons/Res_Analytics/
    - assets/aws_icons/Res_End-User-Computing/
    - assets/aws_icons/Res_Security-Identity-Compliance/
    - assets/aws_icons/Res_Blockchain/
    - assets/aws_icons/Res_Application-Integration/
    - assets/aws_icons/Res_Management-Governance/
    - assets/aws_icons/Res_Networking-Content-Delivery/
    - assets/aws_icons/Res_Storage/
    - assets/aws_icons/Res_Artificial-Intelligence/
    - assets/aws_icons/Res_Containers/
    - assets/aws_icons/Res_General-Icons/
    - assets/aws_icons/Res_Compute/
    - assets/aws_icons/Res_Database/
    - assets/aws_icons/Res_Migration-Modernization/
    - assets/aws_icons/Res_Media-Services/
    - assets/aws_icons/Res_Front-End-Web-Mobile/
    - assets/aws_icons/Res_Developer-Tools/
    - assets/aws_icons/Res_Business-Applications/
